### ISSUE TITLE
'RequestContext' object has no attribute 'META' (Django 1.10)

### ISSUE THREAD

**Issue by sweaver360** [jazzband/django-flatblocks#18]
I just upgraded to Django 1.10 and Flatblocks don't seem to work anymore.  Here's the stack trace:

`File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/mysite/myapp/views.py", line 1432, in sourcing
    return render(request, 'my_page.html', locals())
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flatblocks/templatetags/flatblocks.py", line 91, in flatblock
    result = render_to_string(using, {'flatblock': flatblock}, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/panels/templates/panel.py", line 49, in _request_context_bind_template
    context = processor(self.request)
  File "/usr/local/lib/python2.7/dist-packages/django/template/context_processors.py", line 43, in debug
    if settings.DEBUG and request.META.get('REMOTE_ADDR') in settings.INTERNAL_IPS:
AttributeError: 'RequestContext' object has no attribute 'META'`

Here's how I'm calling it in the template:

`...
{% load flatblocks %}
...
{% flatblock 'my-flatblock' %}`

This all worked fine in Django 1.9.9, but I know Django made some changes to render_to_string's parameters in 1.10, so that's likely the cause.  Thanks.

**Comment by sweaver360** [comment]
I did some more digging and it should be a pretty simple fix.  In flatblocks.py, you'll need to change line 91, which currently looks like this:

`result = render_to_string(using, {'flatblock': flatblock}, context)`

In the [Django 1.9 documentation](https://docs.djangoproject.com/en/1.9/topics/templates/), it had this as the definition for render_to_string:

`render_to_string(template_name, context=None, context_instance=_context_instance_undefined, request=None, using=None)`

In the [Django 1.10 documentation](https://docs.djangoproject.com/en/1.10/topics/templates/), they removed the context_instance parameter, so instead you'll just have to pass the request in (which should be available from the existing context_instance):

`render_to_string(template_name, context=None, request=None, using=None)`

Thanks.

**Comment by sweaver360** [comment]
@funkybob do you know roughly when you'll be able to get around to making this fix?  Are you still supporting django-flatblocks?

**Comment by funkybob** [comment]
This is a cleaner solution, imho... let me know how it goes.

**Comment by sweaver360** [comment]
@funkybob that change seems to work, thanks! Do you know when it will be officially published to PyPI?

**Comment by funkybob** [comment]
I will push a release tonight

**Comment by sweaver360** [comment]
@funkybob thanks for the quick response!
